#baseurl: "https://datapioneers.tech"
baseurl: "."
title: "Data Pioneers 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Data Pioneers"
  Title: "Data Pioneers 2018"
  Description: "A full-day conferene on data science, machine learning and artificial intelligence in industry and business."
  Date: "November 8th 2018, Kempten"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue:
    text: "Allgäu Digital - Digitales Zentrum Schwaben"
    href: "https://standort.allgaeu.de/gruenderzentrum"
  Address: "Keselstraße 16"
  City:  "87435 Kempten (Allgäu)"
  #State: "Quintana"
  Images: ["https://datapioneers.tech/img/badge.png"]
  GoogleMapsKey: "my-secret-maps-key"
  GoogleDomainKey: "4GkTBhQRpMAM6JpHPPGQWmHUD1HTto0vvZjjk890oio"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - organizers
    - partners
    #- sponsors
    - contact
    #- impressum
    #- privacy

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    organizers: "Organizers"
    #impressum: "Impressum"
    #privacy: "Privacy"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "http://datapioneers2018.eventbrite.de/"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Allgäu Digital"
      logo: "/img/logo-ad.png"
      url: "https://standort.allgaeu.de/allgaeudigital"

  # List of Partners
  Partners:
    - name: "Allgäu Digital - Digitales Zentrum Schwaben"
      logo: "/img/partner-ad.png"
      url: "http://www.digital.allgaeu.de"
    - name: "Gründerland Bayern"
      logo: "/img/partner-gb.png"
      url: "https://www.gruenderland.bayern/"
    - name: "Bayerisches Staatsministerium für Wirtschaft, Energie und Technologie"
      logo: "/img/partner-bswet.png"
      url: "https://www.stmwi.bayern.de/"
    - name: "4ländereck Data Science Meetup"
      logo: "/img/partner-4leds.png"
      url: "https://www.meetup.com/4laendereck-Data-Science-Meetup/"
    - name: "Data Science Stammtisch Allgäu"
      logo: "/img/partner-dssallgaeu.png"
      url: "https://www.meetup.com/Data-Science-Stammtisch-Allgau/"

  # The entire schedule
  Schedule:
    - name: "Registration"
      time: "8:45"

    - name: "Welcome"
      time: "9:15"

    - name: "Matthias Anderer"
      photo: "/img/speaker-MatthiasAnderer.png"
      bio: "Innovation and Technology consultant Matthias Anderer supports the leading DAX and MDAX companies like Munich RE, as well as medium-sized companies around Munich. After his studies in aerospace technology (Dipl-Ing. TUM), he worked at Bain & Company (among others) and was part of the establishing team of the TechFounders Startup Program. With his focus on digitalization and artificial intelligence he supports his clients in all upcoming technical and scientific issues."
      company: "Matthias Anderer GmbH"
      link:
        href: "http://www.matthiasanderer.de/"
        text: "Speaker's website"
      presentation:
        title: "Between Dream and Reality - The Long Journey to AI"
        description: "While DeepMind & others weekly release new and more spectecular results, is the German industry regarding AI still at the very beginning. We will examine examples on the subject to understand why >80% of the work depends on data determination and data preparation and clarify the big open questions regarding AI application."
        time: "9:30"
        info: "Opening keynote"

    - name: "Coffee break"
      time: "10:30"

    - name: "Tobias Windisch"
      photo: "/img/speaker-TobiasWindisch.png"
      bio: "Tobias is a python enthusiast working as data scientist at Robert Bosch GmbH. There, he builds machine learning pipelines to derive decisions from large datasets of manufacturing processes automatically. After obtaining his PhD in mathematics, he worked for Daimler TSS GmbH, a subsidiary of Daimler AG, where one of this tasks was to find anomalies in time series data of electric cars."
      company: "Robert Bosch GmbH"
      link:
        href: "http://www.tobias-windisch.de"
        text: "Speaker's website"
      presentation:
        title: "Boosting Assembly Lines with Machine Learning"
        description: "A key challenge in running production lines efficiently is to detect bad parts early in the manufacturing process. Machine learning allows to predict the status of parts, but as bad ones are rare and misclassifying good ones is expensive, finding feasible models is hard. We present how we train and select profitable models to detect bad parts in our assembly processes and show the challenges we faced when dealing with imbalanced datasets from manufacturing lines."
        time: "11:00"

    - name:
      photo: "/img/speaker.png"
      bio: ""
      company: ""
      link:
        href: ""
        text: "Speaker's website"
      presentation:
        title: ""
        description: ""
        time: "11:30"

    - name: "Lunch break"
      time: "12:00"

    - name: "Hannes Sieling"
      photo: "/img/speaker-HannesSieling.png"
      bio: "Hannes is working as an expert data scientist at Blue Yonder in Hamburg, where he develops profound machine learning models for price optimization. From 2005 until 2010 he studied mathematical economics at the University of Göttingen and in 2013 he received his PhD in mathematical statistics for his research on 'Statistical Multiscale Segmentation: Inference, Algorithms and Applications'."
      company: "Blue Yonder GmbH"
      link:
        href: "https://www.xing.com/profile/Hannes_Sieling/"
        text: "Speaker's website"
      presentation:
        title: "Price Optimization: Applied Machine-Learning to drive business decisions"
        description: "The talk guides through the challenges of applying decision-making algorithms based on machine learning to business processes by means of Price Optimization. In the context of Price Optimization accurate demand forecasts enable retailer to find prices according to their business strategy, consumer demand and market conditions. Forecasts for demand and price elasticities are regression tasks that can be addressed by supervised learning algorithms. On the one hand, rare events such as holidays, weather effects, promotions and trends evolving over time require special treatment. On the other hand, the particular use of the forecasts to actively steer prices imposes the substantial challenge to identify the casual effect of price changes to customers’ demand. That is why Data-Scientists involved in Price Optimization face problems that cover exciting parts across areas from statistical learning, discrete optimization, reinforcement learning and many more. A detailed view on these statistical challenges, many practical aspects and insights of the potential of these applications are provided within this talk."
        time: "13:00"

    - name: "Katharina Brunner"
      photo: "/img/speaker-KatharinaBrunner.png"
      bio: "Katharina Brunner is part of the team Data and Digital Investigation at Süddeutsche Zeitung. There, she works at the intersection of traditional reporting, data analysis and data visualization."
      company: "Süddeutsche Zeitung"
      link:
        href: "http://katharinabrunner.de"
        text: "Speaker's website"
      presentation:
        title: "Driven Data Journalism: How data can change reporting"
        description: "Like in many other industries, data driven insights play an ever more important role in journalism. Katharina Brunner will speak about some projects she has been working on at the Süddeutsche Zeitung, one of the largest and most important newspaper in the South of Germany. For example: How to get an idea of the blackbox Facebook? How has the German Parliament changed ever since the AfD entered the scene? And, most important, how to communicate the findings in a non-nerdy way?"
        time: "13:30"

    - name: "Thomas Bühler"
      photo: "/img/speaker-ThomasBuehler.png"
      bio: "Thomas is an AI Researcher at Avira passionate about building large-scale Machine Learning systems for fighting threats in the cyber security space. His goal is to use the latest AI and ML techniques to ensure the best possible protection of Avira's customers. Before joining Avira, he was an academic researcher at Cluster of Excellence MMCI, working on algorithmic and theoretical foundations of Machine Learning. Thomas holds a Dr.rer.nat. and a M.Sc. in Computer Science from Saarland University."
      company: "Avira Operations GmbH & Co. KG"
      link:
        href: "https://www.linkedin.com/in/thomas-buehler/"
        text: "Speaker's website"
      presentation:
        title: "Large-scale Machine Learning based Malware Detection"
        description: "With the emergence of hundreds of thousands of new malware threats every day, the task of providing up-to-date virus definitions becomes increasingly challenging and traditional antivirus techniques alone are not sufficient anymore. In this session we talk about the challenges arising from this adversarial setting. We will then dive in and share some of Avira's decade-long experience in developing large-scale artificial intelligence based antivirus engines for the detection of malicious files."
        time: "14:00"

    - name: "Coffee break"
      time: "14:30"

    - name: "Stefan König"
      photo: "/img/speaker-StefanKoenig.png"
      bio: "Stefan, Manager Data Analytics at sonnen, can indeed be described as a data scientist of the first hour. At Blue Yonder he and his colleagues were among the first to combine scientific algorithms with state-of-the-art software development to take optimal, dynamic decisions for pricing and replenishment. In 2017 he joined sonnen for being able to contribute to a successful energy transition. At sonnen, Stefan and his team employ thorough scientific approaches to turn historic and live measurement data into optimal control signals for sonnenBatteries and sonnenChargers. Stefan holds a PhD in Mathematics from Technische Universität München where his research was concerned with tackling the complexity of high-dimensional optimization problems like they arise in his daily work today."
      company: "sonnen GmbH"
      link:
        href: "http://www.linkedin.com/in/stefanmkoenig"
        text: "Speaker's website"
      presentation:
        title: "Turning Measurements into Optimal Control Signals"
        description: "The heart of sonnen’s products, such as the sonnenBatterie and the sonnenCharger, is to allow their users to optimize the consumption of their self-generated energy. In addition, these devices are also very well suited to offer flexibility to the energy market as they allow a quick and precise reaction to fluctuations of decentralized renewable energy sources. The sonnenBatterie and the sonnenCharger hence come with a charge control that ensures an optimal mix of savings by self-consumed energy and additional revenues from different flexibility markets and grid services. In this talk, I will show how predictions built from historic measurement data are turned into optimal control signals by means of Mathematical Programming."
        time: "15:00"
        info: "Closing keynote"

    - name: "Final words"
      time: "16:00"

    - name: "Networking"
      time: "16:15"

    - name: "Departure to conference dinner"
      time: "17:30"
      info: "Details can be found <a href=\"https://docs.google.com/viewer?url=https://datapioneers.tech/dp2018-dinner.pdf\">here</a>"


  # Organizers:
  Organizers:
    - name: Julia Ehrenmüller
      photo: "img/org-julia.jpg"
      bio: "Julia is an open-minded mathematician, passionate about machine learning, artificial intelligence and data driven business models. She started her career as a researcher in the field of extremal combinatorics and probabilistic graph theory at TU München and TU Hamburg, from where she received her PhD in 2016. Today, Julia works as a Data Scientist in the Innovation Campus at Robert Bosch GmbH, a team employing data mining and machine learning to increase efficiency in manufacturing, thereby actively shaping Industrie 4.0. On a freelance basis, she also supports young companies in building disruptive innovations based on data analysis and predictive modeling. In November 2017, Julia initiated the meet-up Data Science Stammtisch Allgäu, which offers regular talks and networking possibilities for data science enthusiasts in the Allgäu region."
      link:
        href: https://www.linkedin.com/in/juliaehrenmueller/
        text: LinkedIn
    - name: Manuel J. A. Eugster
      photo: "img/org-manuel.jpg"
      bio: "Manuel is a data scientist by heart on the mission of turning data into insights. Currently he leads the Data Analytics & Insights unit at Avira. There he and his team develop data analytics solutions that transform massive amounts of (real-time) data from various sources into knowledge about customers and products. Prior to Avira, he was a scientific researcher at the Probabilistic Machine Learning group at HIIT, Aalto University in Finland and the Department of Statistics at LMU Munich. He worked, among other things, on next generation information retrieval systems using brain-computer interfaces. He holds a PhD in Statistics from LMU Munich, a MSc in Computational Intelligence and a BSc in Software and Information Engineering from TU Vienna."
      link:
        href: https://www.linkedin.com/in/mjaeugster
        text: LinkedIn
    - name: Christian Dosch
      photo: "img/org-christian.jpg"
      bio: "Christian coordinates Allgäu Digital – Digitales Zentrum Schwaben as a project manager. Allgäu Digital is a startup center, incubator and network with the focus on digital business models situated in Kempten, Allgäu. After finishing his studies at the Hochschule der Medien in Stuttgart, he worked project-based for different film and media companies in Munich and Berlin and then passed his experience to other filmmakers as a Film Commissioner in Stuttgart Region. In 2016 he decided to move to the Westallgäu, became self-employed with the Spurfinder UG and nows stands up for putting rural areas on the map of digital transformation and innovation."
      link:
        href: https://www.linkedin.com/in/christiandosch/
        text: LinkedIn
